In [1]:
# Import the necessary dependencies
import pandas as pd

In [2]:
# Read in the data as a DataFrame
# Provide the dataset over AWS S3 bucket. It's ~100 MB.
delayed_flights_url = "https://static.bc-edx.com/ai/ail-v-1-0/m5/lesson_2/delayed_flights.csv"
delayed_flights_df = pd.read_csv(delayed_flights_url)
delayed_flights_df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003,1955,2211.0,2225,WN,335,...,4.0,8,0,N,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754,735,1002.0,1000,WN,3231,...,5.0,10,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628,620,804.0,750,WN,448,...,3.0,17,0,N,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,1829,1755,1959.0,1925,WN,3920,...,3.0,10,0,N,0,2.0,0.0,0.0,0.0,32.0
4,2008,1,3,4,1940,1915,2121.0,2110,WN,378,...,4.0,10,0,N,0,NaN,NaN,NaN,NaN,NaN

In [3]:
# Get the columns
delayed_flights_df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [8]:
# Create a custom function that will calculate of a column from the DataFrame.
def calc_avg(column_values):
    return column_values.mean()

In [16]:
# Show the average time for delayed arrivals (ArrDelay) grouped by each airline carrier.
# Pass the 'ArrDelay' column to the custom function.
# Name the new column "Avg_ArrDelay".
average_time_delay_by_carrier = delayed_flights_df.groupby('UniqueCarrier').apply(lambda grp: calc_avg(grp['ArrDelay']))
average_time_delay_by_carrier

/var/folders/0v/k5cxfnrj4_x27cyj9ynqp8qh0000gn/T/ipykernel_6846/2020060321.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  average_time_delay_by_carrier = delayed_flights_df.groupby('UniqueCarrier').apply(lambda grp: calc_avg(grp['ArrDelay']))

UniqueCarrier
9E    47.996243
AA    47.794556
AQ    21.255376
AS    36.114195
B6    49.455843
CO    38.925122
DL    38.026678
EV    43.735426
F9    26.108155
FL    42.621279
HA    33.811415
MQ    47.349644
NW    45.912690
OH    48.052603
OO    46.396577
UA    49.287229
US    35.113255
WN    30.125680
XE    49.519551
YV    58.518096
dtype: float64

In [13]:
# Use the custom function you created to calculate the average for a DataFrame colummn and
# show the average time for delayed arrivals and departures for each carrier.
avg_delays_by_carrier = delayed_flights_df.groupby('UniqueCarrier').apply(
    lambda grp: pd.Series({
        'Avg_ArrDelay': calc_avg(grp['ArrDelay']),
        'Avg_DepDelay': calc_avg(grp['DepDelay'])
    })
)

print(avg_delays_by_carrier)

               Avg_ArrDelay  Avg_DepDelay
UniqueCarrier
9E                47.996243     48.389124
AA                47.794556     46.840312
AQ                21.255376     26.680000
AS                36.114195     38.888600
B6                49.455843     50.692277
CO                38.925122     41.107583
DL                38.026678     37.734884
EV                43.735426     45.392455
F9                26.108155     25.633450
FL                42.621279     41.083869
HA                33.811415     34.001540
MQ                47.349644     44.996970
NW                45.912690     41.708387
OH                48.052603     46.261080
OO                46.396577     45.184297
UA                49.287229     50.316988
US                35.113255     38.558703
WN                30.125680     34.082782
XE                49.519551     49.275620
YV                58.518096     58.291574

/var/folders/0v/k5cxfnrj4_x27cyj9ynqp8qh0000gn/T/ipykernel_6846/2471917606.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  avg_delays_by_carrier = delayed_flights_df.groupby('UniqueCarrier').apply(

In [14]:
# Create a custom function that returns the total of the items.
def calc_total(column_values):
    return column_values.sum()

In [9]:
# Use the two custom functions you created and show the total number of flights 
# and the average number of flights that were diverted for each flight origin and destination.


# Sort the results in descending order on the new columns, and display the top 25 results.

             Total_Diverted  Avg_Diverted
Origin Dest
DAL    HOU             23.0      0.012432
ORD    LGA             22.0      0.008821
DFW    LGA             21.0      0.016693
BUR    JFK             18.0      0.118421
HLN    MSP             17.0      0.278689
ATL    LGA             17.0      0.008433
BUR    DFW             16.0      0.070796
PHX    ORD             16.0      0.014939
ATL    DFW             15.0      0.009947
SLC    GJT             14.0      0.177215
HRL    HOU             14.0      0.023569
ORD    SNA             14.0      0.022013
HOU    DAL             14.0      0.007110
ORD    DEN             13.0      0.009665
MIA    LGA             12.0      0.014252
PBI    LGA             11.0      0.025057
DTW    MDW             10.0      0.017544
SAN    ORD             10.0      0.016234
MKE    EWR             10.0      0.013966
MCI    MDW             10.0      0.013532
LAS    MDW             10.0      0.013175
LGA    DFW             10.0      0.011806
DTW    LGA             10.0      0.009690
SFO    ORD             10.0      0.007930
LAX    JFK             10.0      0.007570

In [17]:
# Create two more custom functions.
# The first one returns the number of items.
def custom_count(x):
    return x.count

# The second one calculates the percentage.
def custom_percentage(x):
    if x.count()>0:
        return (x.sum() / x.count())* 100

In [20]:
# Show the total number of diverted flights, the total flights, 
# and the percentage of diverted flights for each carrier by day of the week.
diverted_stats = delayed_flights_df.groupby(['UniqueCarrier', 'DayOfWeek']).apply(custom_count)


# Display the top 25 rows. 
top_diverted_stats = diverted_stats.sort_values(by='Total_Diverted', ascending=False).head(25)
print(top_diverted_stats)

/var/folders/0v/k5cxfnrj4_x27cyj9ynqp8qh0000gn/T/ipykernel_6846/440028394.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  diverted_stats = delayed_flights_df.groupby(['UniqueCarrier', 'DayOfWeek']).apply(custom_count)

TypeError: Series.sort_values() got an unexpected keyword argument 'by'